name: ReportGUI
version: 0.0.1
main: net.jp.minecraft.plugin.ReportGUI
commands:
    report:
        description: Provides a Report GUI.
        usage: /report
        permission: report.give
        permission-message: You don't have permission (report.give)
permissions:
    report.open:
        description: Allow open Report GUI.
        default: op
    report.give:
        description: Give a Report GUI stick.
        default: op

